### ISSUE TITLE
Support for Basis/KTX2 supercompressed textures?

### ISSUE THREAD

**Issue by reececomo** [ddenisyuk/gpu-tex-enc#1]
Heya, love your work (I'm coming from the Pixi AssetPack compressed-textures PR [here](https://github.com/pixijs/assetpack/pull/56/files))

Any thought as to possible support for supercompressed [Basis Textures](https://github.com/BinomialLLC/basis_universal)? (re: [@pixi/basis](https://www.npmjs.com/package/@pixi/basis)) Keen to know if these are especially challenging

**Comment by ddenisyuk** [comment]
Hi there! Thanks for your kind words. Adding support for Basis Textures seems straightforward, but I won't be able to implement it in the near future. Contributions are welcome, so feel free to submit a PR!

Moreover, I don't think it is reasonable to update the AssetPack PR until the next one is merged: https://github.com/pixijs/assetpack/pull/69

**Comment by ddenisyuk** [comment]
Check this out: https://github.com/ddenisyuk/gpu-tex-enc/tree/main/packages/%40gpu-tex-enc/basis
v1.2.4 available in npm

**Comment by reececomo** [comment]
You are a legend, thanks @ddenisyuk! I've got a couple custom plugins for assetpack so I'll be on the current "legacy" version for the foreseeable future anyway 😎
